### ISSUE TITLE
telemetry = false in et.cfg does not disable telemetry

### ISSUE THREAD

**Issue by fignew** [MisterTea/EternalTerminal#504] opened 2022-03-20 19:22 UTC
Hello,

When running
`$ et -v 7 --logtostdout 127.0.0.1`
I get the following output:
```
[INFO 2022-03-20 15:14:56,847 client-main ParseConfigFile.hpp:1400] unsupported config line:   ForwardX11 yes, ignored
[INFO 2022-03-20 15:14:56,847 client-main ParseConfigFile.hpp:1400] unsupported config line:   VisualHostKey yes, ignored
[INFO 2022-03-20 15:14:56,847 client-main ParseConfigFile.hpp:1181] /etc/ssh/ssh_config.d/*.confnot found
[INFO 2022-03-20 15:14:56,847 client-main TerminalClientMain.cpp:189] Parsed ssh config file, connecting to 127.0.0.1
[V1 2022-03-20 15:14:56,847 client-main TerminalClientMain.cpp:14] Connecting
[V4 2022-03-20 15:14:56,847 client-main TcpSocketHandler.cpp:83] Before selecting sockFd
[V4 2022-03-20 15:14:56,847 client-main TcpSocketHandler.cpp:87] sockFd 6is selected6
[INFO 2022-03-20 15:14:56,847 client-main TcpSocketHandler.cpp:107] Error connecting with 127.0.0.1: 111 Connection refused
[INFO 2022-03-20 15:14:56,848 client-main TcpSocketHandler.cpp:141] No host found
[V1 2022-03-20 15:14:56,848 client-main TerminalClientMain.cpp:17] Could not connect to host
Could not reach the ET server: 127.0.0.1:2022

Shutting down sentry
```
Seeing "Shutting down sentry" indicates to me that telemetry is still enabled

My et.cfg file is the following:
```
;######################################################################;
;                                                                      ;
;              THIS FILE IS MANAGED BY SALT - DO NOT EDIT              ;
;                                                                      ;
; The contents of this file are managed by Salt. Any changes to this   ;
; file may be overwritten automatically and without warning.           ;
;######################################################################;

[Networking]
port = 2022
# bind_ip = 0.0.0.0

[Debug]
verbose = 0
silent = 0
logsize = 20971520
telemetry = false
```

I've also tried telemetry = 0 and placing the option before and in the [Networking] section.

**Comment by MisterTea** [comment] 2022-03-20 19:47
The problem is that the print you are referring to is outside of the #define that disables telemetry:

https://github.com/MisterTea/EternalTerminal/blob/8ec6b8569430166ec63268e780ee613c37910a2e/src/terminal/TelemetryService.cpp#L79

Please submit a PR that moves that print one line down. Even without your PR, the telemetry is disabled.

**Comment by jshort** [comment] 2022-12-13 19:21
I'm going to close this but I still have a small qualm with the ini file telemetry config:

`telemetry = bool(stoi(ini.GetValue("Debug", "Telemetry", "1")));`

The cxxopts option is assumed to be a boolean but the ini parser logic uses stoi to convert the parsed char* to an int.  We should probably support both literal booleans and integer equivalents (0 - false, non-zero - true).

**Closed by jshort** 2022-12-13 19:21 UTC
