### ISSUE TITLE
etserver blocks shutdown

### ISSUE THREAD

**Issue by gogodave** [MisterTea/EternalTerminal#546] opened 2022-11-17 13:44 UTC
When using etserver with systemd service, the process does not respond to sigterm and causes shutdown to be delayed until systemd times out and sends sigkill.

Nov 17 08:07:54 bomba systemd[1]: Started Eternal Terminal.
Nov 17 08:12:49 bomba systemd[1]: Stopping Eternal Terminal...
Nov 17 08:14:19 bomba systemd[1]: et.service: State 'stop-sigterm' timed out. Killing.
Nov 17 08:14:19 bomba systemd[1]: et.service: Killing process 997 (etserver) with signal SIGKILL.
Nov 17 08:14:19 bomba systemd[1]: et.service: Killing process 1056 (etserver) with signal SIGKILL.
Nov 17 08:14:19 bomba systemd[1]: et.service: Main process exited, code=killed, status=9/KILL
Nov 17 08:14:19 bomba systemd[1]: et.service: Failed with result 'timeout'.
Nov 17 08:14:19 bomba systemd[1]: Stopped Eternal Terminal.

**Comment by jshort** [comment] 2022-11-30 17:44
@gogodave can you attach the /tmp/etserver.* logs to this task at the time you attempt to stop the systemd service?

**Comment by jshort** [comment] 2022-12-07 17:44
@gogodave can you update your systemd service ExecStart config to make sure you do *not* have `--daemon` in the start command?  If you do, then as soon as systemd starts etserver, the process will fork and continue to run but systemd has 'lost' it since the parent/original process will exit shortly thereafter.  This was fixed in a recent PR.

**Comment by chy-causer** [comment] 2022-12-12 20:34
I can replicate this issue on two computers that I own. No --daemon specified, and all pretty much stock apart from adding --logtostdout to the unitfile.


## Unitfile
```
# /lib/systemd/system/et.service
[Unit]
Description=Eternal Terminal
After=syslog.target network.target

[Service]
Type=simple
Restart=on-failure
ExecStart=/usr/bin/etserver --cfgfile=/etc/et.cfg

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/et.service.d/override.conf
[Service]
ExecStart=
ExecStart=/usr/bin/etserver --cfgfile=/etc/et.cfg --logtostdout
```


## Logs
```
# journalctl -u et -f
Dec 12 20:26:18  systemd[1]: et.service: Failed with result 'timeout'.
Dec 12 20:26:18  systemd[1]: Stopped Eternal Terminal.
Dec 12 20:26:18  systemd[1]: et.service: Consumed 1.633s CPU time.
Dec 12 20:26:18  systemd[1]: Started Eternal Terminal.
Dec 12 20:26:18  etserver[54370]: [INFO 2022-12-12 20:26:18,413 etserver-main TerminalServerMain.cpp:185] In child, about to start server.
Dec 12 20:26:18  etserver[54370]: [INFO 2022-12-12 20:26:18,413 etserver-main TcpSocketHandler.cpp:224] Listening on 0.0.0.0:2022/2/1/6
Dec 12 20:26:18  etserver[54370]: [INFO 2022-12-12 20:26:18,413 etserver-main TcpSocketHandler.cpp:224] Listening on 0.0.0.0:2022/10/1/6
Dec 12 20:26:18  etserver[54370]: [INFO 2022-12-12 20:26:18,413 etserver-main TerminalServer.cpp:23] Creating server
Dec 12 20:27:57  etserver[54370]: Shutting down sentry
Dec 12 20:27:57  systemd[1]: Stopping Eternal Terminal...
Dec 12 20:29:28  systemd[1]: et.service: State 'stop-sigterm' timed out. Killing.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54370 (etserver) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54373 (etserver) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54376 (etserver) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54378 (etserver) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54379 (n/a) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Killing process 54380 (etserver) with signal SIGKILL.
Dec 12 20:29:28  systemd[1]: et.service: Main process exited, code=killed, status=9/KILL
Dec 12 20:29:28  systemd[1]: et.service: Failed with result 'timeout'.
Dec 12 20:29:28  systemd[1]: Stopped Eternal Terminal.
Dec 12 20:29:28  systemd[1]: et.service: Consumed 1.010s CPU time.
Dec 12 20:29:28  systemd[1]: Started Eternal Terminal.
Dec 12 20:29:28  etserver[54414]: [INFO 2022-12-12 20:29:28,159 etserver-main TerminalServerMain.cpp:185] In child, about to start server.
Dec 12 20:29:28  etserver[54414]: [INFO 2022-12-12 20:29:28,160 etserver-main TcpSocketHandler.cpp:224] Listening on 0.0.0.0:2022/2/1/6
Dec 12 20:29:28  etserver[54414]: [INFO 2022-12-12 20:29:28,160 etserver-main TcpSocketHandler.cpp:224] Listening on 0.0.0.0:2022/10/1/6
Dec 12 20:29:28  etserver[54414]: [INFO 2022-12-12 20:29:28,160 etserver-main TerminalServer.cpp:23] Creating server
```
## Version

```
# dpkg -l | grep '\bet\b'
ii  et                                               6.2.1-jammy2                                amd64        Remote terminal for the busy and impatient
```

## Config file

```
cat /etc/et.cfg 
; et.cfg : Config file for Eternal Terminal
;

[Networking]
port = 2022
# bind_ip = 0.0.0.0

[Debug]
verbose = 0
silent = 0
logsize = 20971520
telemetry = 1
```

**Comment by jshort** [comment] 2022-12-14 23:48
And to repro, you are simply running `sudo systemctl stop et`?

**Comment by chy-causer** [comment] 2022-12-15 09:54
Hi, thanks for getting back.

```
$ cat /etc/apt/sources.list.d/jgmath2000-ubuntu-et-kinetic.list 

deb https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu/ kinetic main
# deb-src https://ppa.launchpadcontent.net/jgmath2000/et/ubuntu/ kinetic main


$ dpkg -l | grep '\bet\b'

ii  et                                         6.2.1-kinetic2                           amd64        Remote terminal for the busy and impatient
```

Yes, it is 100% reproducible using systemctl

```
$ time sudo systemctl stop et

real	1m30.056s
user	0m0.002s
sys	0m0.002s
```

I have a Kinetic box and a Jammy box. Both do it.

**Comment by jshort** [comment] 2022-12-15 19:26
I can repro on my CentOS 8 box.  SIGTERM does nothing...but it does invoke the Sentry/Telemetry shutdown logic so we might need to make sure the SIGTERM logic for telemetry is not interfering with the standard SIGTERM behavior for `etserver`.

**Comment by jshort** [comment] 2022-12-15 19:57
Ok it is the TelemetryService.  If I run `sudo ET_NO_TELEMETRY=true etserver --cfgfile /etc/et.cfg --logtostdout`, then SIGTERM will kill the service.  Let me look at the signal handling logic to make it work with or without telemetry enabled.

**Comment by chy-causer** [comment] 2022-12-15 20:33
> Ok it is the TelemetryService. If I run `sudo ET_NO_TELEMETRY=true etserver --cfgfile /etc/et.cfg --logtostdout`, then SIGTERM will kill the service. Let me look at the signal handling logic to make it work with or without telemetry enabled.

Nice one! This fixes the issue for me, as the following output shows

```
$ time sudo systemctl restart et

real	0m0.012s
user	0m0.002s
sys	0m0.002s



$ sudo systemctl cat et
# /lib/systemd/system/et.service
[Unit]
Description=Eternal Terminal
After=syslog.target network.target

[Service]
Type=simple
Restart=on-failure
ExecStart=/usr/bin/etserver --cfgfile=/etc/et.cfg

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/et.service.d/override.conf
[Service]
Environment=ET_NO_TELEMETRY=true
```

**Comment by jshort** [comment] 2022-12-15 21:09
@chy-causer Yes! I was going to recommend this as a workaround for you or @gogodave until I get the signal handling logic sorted.  I'll reference this issue in the PR so you can review it.

**Closed** 2022-12-19 17:11 UTC
